### PR TITLE
DC-5 load non-blocking partial with Html and X-Title

### PR DESCRIPTION
**Pull request by kasia-kittel**

### CODE REVIEW

**Comment by xnejp03** [comment]
This should be reworked so that the asynch call is used in the main get() method. In any case, this library deals with cached content mostly, so asynch calls can be avoided if the partials are static / can be easily parametrised.

**Comment by diksta** [comment]
Picking this up as it seems to have gone dead.

In our case the partials we are processing are never cached, so having the library blocking while they are processed is not what we are after.

The partials are the content which is likely to change during the users session, and is unlikely to be requested more than once on the same service instance.

Are you suggesting we should not be using this library to get uncached partials like this? We need to get these partials in both YTA and PTA, so using a common library would make sense, if not this one then we can create a new one instead that does the same thing but future based.

Also, we need to know a little bit more about the response than just the HTML body, the current API isn't very extensible, so we have introduced the Partial case class that can contain other pertinent details.

**Comment by diksta** [comment]
Have talked to Kasia and she has explained she already discussed this with you. 

She is going to put some changes in to clearly separate the future based partial code.

Hopefully that will be a better solution and clearly delineate the future base call from the existing cache based request.

**Comment by xnejp03** [comment]
This has been replaced by PR #7

**Pull request closed without merging**
